all: kruskaldriver

kruskaldriver:kruskaltest.cpp Graph.cpp Graph.h DisjointSet.cpp DisjointSet.h SortingAlgorithms.h
	g++ -std=c++11 -o kruskaldriver kruskaltest.cpp Graph.cpp DisjointSet.cpp SortingAlgorithms.h

clean:
	rm kruskaldriver
